spring:
  profiles:
    active: dev
---
spring:
  profiles: dev # 开发环境
  application:
    name: suda-config-service-dev

---
spring:
  profiles: sit # 测试环境
  application:
    name: suda-config-service-sit